export const navigation = {
  primary: [
    { label: "Dashboard", href: "/dashboard" },
    { label: "Gateway Settings", href: "/settings", permission: "gateway.config.read" },
    { label: "Audit Logs", href: "/audit-logs", permission: "audit.read" },
    { label: "Users", href: "/admin/users", permission: "user.manage" },
    { label: "Roles", href: "/admin/roles", permission: "role.manage" },
    { label: "Groups", href: "/admin/groups", permission: "group.manage" },
    { label: "SSO Settings", href: "/admin/sso", permission: "sso.manage" },
    { label: "SCIM", href: "/admin/scim", permission: "scim.manage" },
    { label: "Products", href: "/admin/products", permission: "product.manage" },
    { label: "Services", href: "/admin/services", permission: "service.manage" },
    { label: "Endpoints", href: "/admin/endpoints", permission: "endpoint.manage" },
    { label: "Clients", href: "/admin/clients", permission: "client.manage" },
    { label: "Client Permissions", href: "/admin/client-permissions", permission: "client.permission.manage" },
    { label: "User Profiles", href: "/admin/user-profiles", permission: "user.profile.manage" },
    { label: "Test Console", href: "/console", permission: "endpoint.manage" },
    { label: "Keys", href: "/admin/keys", permission: "key.revoke" },
    { label: "Metrics", href: "/admin/metrics", permission: "observability.read" },
    { label: "Traces", href: "/admin/traces", permission: "observability.read" },
    { label: "Gateway Logs", href: "/logs", permission: "observability.read" },
    { label: "Alerts", href: "/admin/alerts", permission: "alerts.manage" },
    { label: "Specs", href: "/admin/specs", permission: "spec.manage" },
    { label: "Announcements", href: "/admin/announcements", permission: "announcement.manage" },
    { label: "Maintenance", href: "/admin/maintenance", permission: "gateway.config.write" },
    { label: "Bulk Ops", href: "/admin/bulk", permission: "bulk.manage" },
    { label: "Tenants", href: "/admin/tenants", permission: "tenant.manage" },
  ],
  secondary: [
    { label: "Profile", href: "/profile" },
  ],
};
